module.exports = {
  apps: [
    {
      name: 'korean-chatbot-backend',
      cwd: __dirname,
      script: 'uvicorn',
      args: 'app.main:app --host 0.0.0.0 --port 9000',
      interpreter: 'none',
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
      env: { PYTHONPATH: __dirname },
      log_file: '/tmp/korean-chatbot-backend.log',
      error_file: '/tmp/korean-chatbot-backend-err.log',
      out_file: '/tmp/korean-chatbot-backend-out.log',
    },
    {
      name: 'korean-chatbot-frontend',
      cwd: __dirname + '/frontend',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
      log_file: '/tmp/korean-chatbot-frontend.log',
      error_file: '/tmp/korean-chatbot-frontend-err.log',
      out_file: '/tmp/korean-chatbot-frontend-out.log',
    },
  ],
};
